### ISSUE TITLE
安装的时候出现错误   哪位大神看看这是什么问题

### ISSUE THREAD

**Issue by molandtoxx** [JoneXiong/oejia_weshop#18]
Odoo Server Error
Traceback (most recent call last):
  File "/data/odoo12/odoo12-server/odoo/http.py", line 656, in _handle_exception
    data-pjax
  File "/data/odoo12/odoo12-server/odoo/http.py", line 314, in _handle_exception
    In this repository
  File "/data/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/odoo12/odoo12-server/odoo/http.py", line 698, in dispatch
    <relative-time datetime="2019-06-13T16:18:17Z" class="no-wrap">Jun 13, 2019</relative-time>
  File "/data/odoo12/odoo12-server/odoo/http.py", line 346, in _call_function
    </div>
  File "/data/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/odoo12/odoo12-server/odoo/http.py", line 339, in checked_call
  File "/data/odoo12/odoo12-server/odoo/http.py", line 941, in __call__
    <tr>
  File "/data/odoo12/odoo12-server/odoo/http.py", line 519, in response_wrap
    data-pjax="#js-repo-pjax-container">
  File "/data/odoo12/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/data/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/odoo12/odoo12-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/odoo12/odoo12-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/data/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/data/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/data/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/odoo12/odoo12-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/data/odoo12/odoo12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/data/odoo12/odoo12-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/data/odoo12/odoo12-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/data/odoo12/odoo12-server/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/data/odoo12/odoo12-server/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: 模块加载 oejia_weshop 失败: 文件 oejia_weshop/security/ir.model.access.csv 无法处理:
 在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_banner'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_banner'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_payment'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_product_category'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_product_category'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_user'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_province'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_province'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_city'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_city'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_district'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_district'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_shipper'
在字段'Object'中没找到匹配的记录外部 ID 'model_oe_shipper'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_banner'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_notice'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_notice'
在字段'Object'中没找到匹配的记录外部 ID 'model_wxapp_product_category'
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值

**Comment by JoneXiong** [comment]
模块没加载成功，一般是依赖的第三方库没安装导致
